CREATE TABLE Users 
(
    id GUID PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Login VARCHAR(255) NOT NULL,
    Password VARCHAR(16) NOT NULL,
    PhoneNumber VARCHAR(10) NOT NULL,
    CompanyID GUID,
    IsBoss BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE Company
(
    id GUID PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    BigBoss GUID,
    Country VARCHAR(255) NOT NULL
);